// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Feed is the predicate function for feed builders.
type Feed func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)
