// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Subscription is the predicate function for subscription builders.
type Subscription func(*sql.Selector)
